### ISSUE TITLE
Color property does not work.

### ISSUE THREAD

**Issue by msembinelli** [kirillshevch/react-cryptocoins#1]
Hi,

I am developing a reactJS application and would like to display the SVG cryptocoin icons with their native colors.

The example outlined in the README does not work for me. Is there anything special I have to do? Do I have to include the cryptocoins-colors.css?

> <Icon.Eth color="red" size={48} />

Thanks!

**Comment by kirillshevch** [comment]
@msembinelli Thanks, I'll fix it soon

**Comment by msembinelli** [comment]
If you want, I can take a stab at fixing it and create a PR. I wouldn't mind if that would be more convenient!

EDIT: NVM, I see you're already working on it.

**Comment by kirillshevch** [comment]
if you can do it I will be grateful :)

**Comment by msembinelli** [comment]
I will give it a shot!
